FROM openjdk:8-jre-alpine
ADD ./apache-skywalking-apm-incubating-5.0.0-alpha.tar.gz /
COPY ./skywalking-webappService.sh /apache-skywalking-apm-incubating/bin/webappService.sh
COPY ./skywalking-startup.sh /apache-skywalking-apm-incubating/bin/startup.sh
ENV TIME_ZONE Asia/Shanghai
RUN apk add --no-cache tzdata && \
 echo "${TIME_ZONE}" > /etc/timezone && \
 ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime
ENTRYPOINT /apache-skywalking-apm-incubating/bin/startup.sh

EXPOSE 9920 9921 9922 9923
